---
title: "Graphics with ggplot"
author: "Ken"
date: "12 March 2018"
output: html_document
---

#learning ggplot2 

```{r, echo=FALSE}
library(tidyverse)
library(ggthemes)
```

```{r}
mpg
```
```{r}
myplot <- ggplot(data=mpg, mapping=aes(x=displ,y=hwy)) +
geom_point(alpha=0.4)  + 
theme_classic()
myplot

```
```{r}
ggplot(mpg,aes(x=displ,y=hwy,color=class)) + geom_point() +
  theme_classic()
```

```{r}
ggplot(mpg,aes(x=hwy,y=cty,size=class,color=fl)) + geom_point() +
  theme_classic()
```

```{r}
ggplot(mpg,aes(x=displ,y=hwy,label=seq(nrow(mpg)))) +
  geom_text() +
  theme_classic()
```
try some facets
```{r}
ggplot(mpg,aes(x=displ,y=hwy,color= class)) +
  geom_point() +
  facet_wrap( ~ year) +
  theme_classic()

```
Try some boxplots
```{r}
ggplot(mpg,aes(x=year,y=hwy,group=year)) +
  geom_boxplot() +
  facet_grid( ~ class) +
  theme_classic()

```
Do some regression lines 
```{r}
ggplot(mpg,aes(x=displ,y=hwy,group=year)) +
  geom_point() +
  geom_smooth() +
  #facet_grid( ~ class) +
  theme_classic()

```
other geometries
```{r}
ggplot(mpg,aes(x=drv,y=hwy)) +
  geom_violin() +
  #facet_grid( ~ class) +
  theme_classic()

```

change some labels
```{r}
ggplot(mpg,aes(x=displ,y=hwy)) +
  geom_point() +
  geom_smooth() +
  labs(title="Displacement v highway mileage",x="Engine Size",y="Miles per Gallon") +
  theme_classic()

```

Set a general theme
```{r} 
mytheme <- theme_classic() + 
  theme(text=element_text(size=16))
ggplot(mpg,aes(x=displ,y=hwy)) +
  geom_point() +
  mytheme
```
Do some Barplots

```{r}
ggplot(mpg,aes(x=fl,fill=class)) +
  geom_bar(position="dodge") +
  mytheme
```

Export some plots

```{r}
myplot <- ggplot(mpg,aes(x=fl,fill=class)) +
  geom_bar(position="fill") +
  mytheme
ggsave("barplot.pdf",plot=myplot,device="pdf",height=10,width=10,units="cm")
```